Staff/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^System/', include('System.urls', namespace='sta'))
]

System/urls.py
from django.conf.urls import url

from System import views

urlpatterns = [
    url(r'userRegist/', views.userRegist, name='userRegist'),
    url(r'userLogin/', views.userLogin, name='userLogin'),
    url(r'^userList/', views.userList, name='userList'),
    url(r'userAdd/', views.userAdd, name='userAdd'),
    url(r'userDelete/', views.userDelete, name='userDelete'),
    url(r'userUpdate/', views.userUpdate, name='userUpdate'),

    # url(r'fenye/', views.fenye, name='page'),
]

System/models.py
from django.db import models


# Create your models here.
class Emp(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    gender = models.BooleanField(default=True)

    class Meta:
        db_table = 'staff'


class User(models.Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=255)
    tickek = models.CharField(max_length=30,null=True)

    class Meta:
        db_table = 'users'

System/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from System.models import Emp, User


def userList(request):
    # 获取数据
    emp = Emp.objects.all()
    # 页码
    page = int(request.GET.get("page", 1))
    # 每一页数据
    per_page = request.GET.get("per_page", 4)
    # 分页器
    paginator = Paginator(emp, per_page)
    # 单页数据
    page_single = paginator.page(page)
    # page_single.has_previous()
    # page_single.has_next()
    # page_single.previous_page_number()
    # page_single.next_page_number()

    return render(request,'userList.html',locals())


def userAdd(request):
    if request.method == 'GET':
        return render(request, 'userAdd.html')
    elif request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        gender = request.POST.get('gender')

        emp = Emp()
        emp.name = name
        emp.age = age
        emp.gender = gender
        emp.save()
        return redirect(reverse('sta:userList'))


def userDelete(request, ):
    id = request.GET.get('id')
    emp = Emp.objects.get(pk=id)
    emp.delete()
    return redirect(reverse('sta:userList'))


def userUpdate(request):
    if request.method == 'GET':
        id = request.GET.get('id')
        emp = Emp.objects.get(pk=id)
        context = {
            'emp': emp
        }
        return render(request, 'userUpdate.html', context=context)
    elif request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        gender = request.POST.get('gender')

        id = request.POST.get('id')
        emp = Emp.objects.get(pk=id)
        emp.name = name
        emp.age = age
        emp.gender = gender
        emp.save()

        return redirect(reverse('sta:userList'))


# def fenye(request):
    # # 获取数据
    # emp = Emp.objects.all()
    # # 页码
    # page = int(request.GET.get("page", 1))
    # # 每一页数据
    # per_page = request.GET.get("per_page", 4)
    # # 分页器
    # paginator = Paginator(emp, per_page)
    # # 单页数据
    # page_single = paginator.page(page)
    # return redirect(reverse('sta:userList'),locals())

    # book_list = []
    # '''
    # 数据通常是从 models 中获取。这里为了方便，直接使用生成器来获取数据。
    # '''
    # for x in range(1, 26):  # 一共 25 本书
    #     book_list.append('Book ' + str(x))
    # # emp = Emp.objects.all()
    #
    # # 将数据按照规定每页显示 10 条, 进行分割
    # paginator = Paginator(book_list, 5)
    #
    # if request.method == "GET":
    #     # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
    #     page = request.GET.get('page')
    #     try:
    #         books = paginator.page(page)
    #     #
    #     except PageNotAnInteger:
    #         # 如果请求的页数不是整数, 返回第一页。
    #         books = paginator.page(1)
    #     except InvalidPage:
    #         # 如果请求的页数不存在, 重定向页面
    #         return HttpResponse('找不到页面的内容')
    #     except EmptyPage:
    #         # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
    #         books = paginator.page(paginator.num_pages)
    #
    # template_view = 'page.html'
    # return render(request, template_view, {'books': books})

    # if request.method == 'POST':
    #     emp = Emp.objects.all()
    #     paginagtor = Paginator(emp, 4)
    #     pager = paginagtor.page(page)
    #     pager.has_previous()
    #     pager.has_next()
    #     pager.previous_page_number()
    #     pager.next_page_number()
    #     return redirect(reverse('sta:page'))


def userRegist(request):
    if request.method == 'GET':
        return render(request, 'userRegist.html')
    # if request.method == 'POST':
    #     name = request.POST.get('name')
    #     password = request.POST.get('password')
    #     request.session['name'] = name
    #
    #     password = make_password(password)
    #     User.objects.create(name=name, password=password)
    #     return redirect(reverse('sta:userLogin'))
    if request.method == 'POST':
        name = request.POST.get('name')
        password = request.POST.get('password')
        password = make_password(password)
        user = User()
        user.name = name
        user.password = password
        user.save()
        return render(request, 'userLogin.html')


def userLogin(request):
    if request.method == 'GET':
        return render(request, 'userLogin.html')
    # if request.method == 'POST':
    #     name = request.POST.get('name')
    #     password = request.POST.get('password')
    #
    #     if User.objects.filter(name=name).exists():
    #         return render(request, 'userLogin.html', {'password': '用户密码错误'})
    #
    #     if check_password(password, User.password):
    #
    #         return redirect(reverse('sta:userList'))
    #     else:
    #         return render(request, 'userList.html', context=locals() )
    if request.method == 'POST':
        name = request.POST.get('name')
        passwd = request.POST.get('password')
        user = User.objects.get(name=name)

        if check_password(passwd, user.password):
            # if passwd == user.password:
            return redirect(reverse('sta:userList'))
        else:
            return HttpResponse('密码不正确')

templates/fenye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<br>
<div class="text-center">
    {% for book in books %}
        <span>书名： {{ book }} <br/></span>
    {% endfor %}
</div>

{# 实现分页标签的代码 #}
{# 这里使用 bootstrap 渲染页面 #}
<div id="pages" class="text-center">
    <nav>
        <ul class="pagination">
            <li class="step-links">
                {% if books.has_previous %}
                    <a class='active' href="?page={{ books.previous_page_number }}">上一页</a>
                {% endif %}

                <span class="current">
                    Page {{ books.number }} of {{ books.paginator.num_pages }}</span>

                {% if books.has_next %}
                    <a class='active' href="?page={{ books.next_page_number }}">下一页</a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>

{#<form action="{% url 'sta:page' %}" method="post">#}
{#    <table>#}
{#        <tr>#}
{#            <td>用户名</td>#}
{#            <td>密码</td>#}
{#        </tr>#}
{#        {% for user in pager.object_list %}#}
{#            <tr>#}
{#                <td>{{ user.name }}</td>#}
{#                <td>{{ user.age }}</td>#}
{#                <td>{{ user.gender }}</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{##}
{#    </table>#}
{#    <div>#}
{#        {% for page in paginagtor.page_range %}#}
{#            {{ page }}#}
{#        {% endfor %}#}
{##}
{#    </div>#}
{#</form>#}
</body>
</html>

templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页</title>
</head>
<body>
<h1>今日热映</h1>
<ul>
    {% for emp in page_single.object_list %}
        <li>{{ emp.name }}</li>
    {% endfor %}
    
</ul>

{% for foo in paginator.page_range %}
    <a href="{% url 'sta:page'  %}?page={{ foo }}">{{ foo }}</a>
{% endfor %}


{#<br>#}
{#<div class="text-center">#}
{#    {% for book in books %}#}
{#        <span>书名： {{ book }} <br/></span>#}
{#    {% endfor %}#}
{#</div>#}
{##}
{# 实现分页标签的代码 #}
{# 这里使用 bootstrap 渲染页面 #}
{#<div id="pages" class="text-center">#}
{#    <nav>#}
{#        <ul class="pagination">#}
{#            <li class="step-links">#}
{#                {% if books.has_previous %}#}
{#                    <a class='active' href="?page={{ books.previous_page_number }}">上一页</a>#}
{#                {% endif %}#}
{##}
{#                <span class="current">#}
{#                    Page {{ books.number }} of {{ books.paginator.num_pages }}</span>#}
{##}
{#                {% if books.has_next %}#}
{#                    <a class='active' href="?page={{ books.next_page_number }}">下一页</a>#}
{#                {% endif %}#}
{#            </li>#}
{#        </ul>#}
{#    </nav>#}
{#</div>#}

{#<form action="{% url 'sta:page' %}" method="post">#}
{#    <table>#}
{#        <tr>#}
{#            <td>用户名</td>#}
{#            <td>密码</td>#}
{#        </tr>#}
{#        {% for user in pager.object_list %}#}
{#            <tr>#}
{#                <td>{{ user.name }}</td>#}
{#                <td>{{ user.age }}</td>#}
{#                <td>{{ user.gender }}</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{##}
{#    </table>#}
{#    <div>#}
{#        {% for page in paginagtor.page_range %}#}
{#            {{ page }}#}
{#        {% endfor %}#}
{##}
{#    </div>#}
{#</form>#}
</body>
</html>

templates/regist.html
<html>
<head>
    <title>regist</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    {#		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />#}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
    <div class="alert alert-primary" role="alert">
      A simple primary alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-secondary" role="alert">
      A simple secondary alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-success" role="alert">
      A simple success alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-danger" role="alert">
      A simple danger alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-warning" role="alert">
      A simple warning alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-info" role="alert">
      A simple info alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
    <div class="alert alert-light" role="alert">
      A simple light alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
    </div>
<div class="alert alert-dark" role="alert">
  A simple dark alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
</div>

    <script src="/static/js/jquery.slim.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>


templates/userAdd.html
{% load static %}
<html>
<head>
    <title>regist</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">Revolution</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>

        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                添加员工
            </h1>
            <form action="{% url 'sta:userAdd' %}" method="post">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">
                            用户名:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="name"/>
                        </td>
                    </tr>


                    <tr>
                        <td valign="middle" align="right">
                            年龄:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="age"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            性别:
                        </td>
                        <td valign="middle" align="left">
                            男
                            <input type="radio" class="inputgri" name="gender" value="1"
                                   checked="checked"/>
                            女
                            <input type="radio" class="inputgri" name="gender" value="0"/>
                        </td>
                    </tr>


                </table>
                <p>
                    <input type="submit" class="button" value="添加 &raquo;"/>
                </p>
            </form>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            HJH@10000.COM
        </div>
    </div>
</div>
</body>
</html>

templates/userList.html
{% load static %}
<html>
<head>
    <title>emplist</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2020/9/10
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">Revolution</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>

        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                员工管理系统
            </h1>
            <table class="table">
                {#						<tr class="table_header">#}
                <td>
                    ID
                </td>
                <td>

                    姓名

                </td>
                <td>
                    性别
                </td>
                <td>
                    年龄
                </td>
                <td>
                    操作

                </td>
                {#						</tr>#}
                {#                {% for emp in emp_list %}#}
                {% for emp in page_single.object_list %}


                    <tr class="row1">
                        <td>
                            {{ emp.id }}
                        </td>
                        <td>
                            {{ emp.name }}
                        </td>
                        <td>
                            {% if  emp.gender %}
                                男
                            {% else %}
                                女
                            {% endif %}

                        </td>
                        <td>
                            {{ emp.age }}
                        </td>

                        <td>
                            <a href="{% url 'sta:userDelete' %}?id={{ emp.id }}">删除</a>
                            <a href='{% url "sta:userUpdate" %}?id={{ emp.id }}'>修改</a>
                        </td>
                    </tr>
                {% endfor %}

            </table>
            <p>
                <a href="{% url 'sta:userAdd' %}">添加员工</a>

            </p>
            <div>

                    {% if page_single.has_previous %}
                        <a class='active' href="?page={{ page_single.previous_page_number }}">上一页</a>
                    {% endif %}
                    {% for foo in paginator.page_range %}
                        <a href="{% url 'sta:userList' %}?page={{ foo }}">{{ foo }}</a>
                    {% endfor %}
                    {% if page_single.has_next %}
                        <a class="active" href="?page={{ page_single.next_page_number }}">下一页</a>
                    {% endif %}

                {#                <div>#}
                {#                    {% if page_single.has_previous %}#}
                {#                        <a href="{% url 'sta:userList' %}{{ page_single.previous_page_number }}">上一页</a>#}
                {#                    {% endif %}#}
                {#                </div>#}


            </div>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            1602460860@qq.com(京)-经营性-2017-0020京公网安备11000002000001号
        </div>
    </div>
</div>
</body>
</html>

templates/userLogin.html
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
							2009/11/20
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">Main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						登录
					</h1>
					<form action="{% url 'sta:userLogin' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>

							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="password" />
								</td>
							</tr>





						</table>
						<p>
							<input type="submit" class="button" value="点击登录 &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/userRegist.html
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
							2009/11/20
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">Main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						注册
					</h1>
					<form action="{% url 'sta:userRegist' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>

							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="password" />
								</td>
							</tr>





						</table>
						<p>
							<input type="submit" class="button" value="点击注册 &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					ABC@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/userUpdate.html
{% load static %}
<html>
<head>
    <title>regist</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">Revolution</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>

        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                修改员工系统
            </h1>
            <form action="{% url 'sta:userUpdate' %}" method="post">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">
                            ID:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="id" readonly value="{{ emp.id }}"/>
                        </td>
                    </tr>

                    <tr>
                        <td valign="middle" align="right">
                            用户名:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="name" value="{{ emp.name }}"/>
                        </td>
                    </tr>


                    <tr>
                        <td valign="middle" align="right">
                            年龄:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="age" value="{{ emp.age }}"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            性别:
                        </td>
                        {% if emp.gender %}
                            <td valign="middle" align="left">
                            男
                            <input type="radio" class="inputgri" name="gender" value="1"
                                   checked="checked"/>
                            女
                            <input type="radio" class="inputgri" name="gender" value="0"/>
                        </td>
                            {% else %}
                            <td valign="middle" align="left">
                            男
                            <input type="radio" class="inputgri" name="gender" value="1"
                                   />
                            女
                            <input type="radio" class="inputgri" name="gender" value="0" checked="checked"/>
                        </td>
                        {% endif %}

                    </tr>


                </table>
                <p>
                    <input type="submit" class="button" value="修改 &raquo;"/>
                </p>
            </form>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            HJH@10000.COM
        </div>
    </div>
</div>
</body>
</html>